#include "../single.h"

#ifndef LOREM_H
#define LOREM_H
const char *LOREMIPSUM[] = 
{
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ligula lorem, fringilla at metus ac, volutpat porttitor urna. Nunc tempor mi vel lorem facilisis lobortis. Nulla facilisi. Praesent vehicula felis eget risus iaculis aliquet. Cras venenatis sagittis magna in sollicitudin. Quisque porttitor ut diam id sagittis. Ut cursus rhoncus dui, et faucibus neque rutrum nec. Mauris venenatis nulla nec nisi mattis, fringilla cursus urna porta. Maecenas euismod varius commodo. Phasellus et magna libero. Curabitur non posuere lectus. Aenean at sodales mi. Nunc vestibulum ornare sagittis. Donec scelerisque, massa eu vehicula consectetur, nulla ipsum lobortis arcu, non malesuada lectus neque et tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed vulputate dictum ligula, eget laoreet dui vulputate at. ",
	"Cras tincidunt orci ipsum, nec cursus massa volutpat eu. Quisque magna sem, sollicitudin eleifend posuere at, venenatis vel urna. Praesent malesuada felis elit, non tincidunt velit sagittis vitae. Etiam sit amet lectus felis. Curabitur dapibus neque condimentum aliquam dictum. Nulla aliquet orci sed suscipit ornare. Nunc accumsan sit amet ante eget consectetur. ",
	"Donec consectetur elit id scelerisque volutpat. Vestibulum turpis lacus, consequat non fringilla sed, lobortis et risus. Aliquam dapibus nunc sit amet eros placerat placerat. Fusce efficitur nisi id viverra ultrices. Aliquam maximus leo eget erat dapibus ultricies. Sed placerat at diam ac imperdiet. Vestibulum sit amet venenatis ligula. Nullam tristique, ante et semper imperdiet, turpis tellus porttitor dolor, quis euismod lacus nunc in nibh. Phasellus eu dapibus mauris. Vestibulum fermentum, nibh eget tincidunt pellentesque, tellus nisl cursus ligula, a aliquet erat enim vel purus. Integer tellus ex, maximus id leo pulvinar, consequat ultrices eros. Suspendisse vel dolor ullamcorper, varius orci et, accumsan lacus. ",
	"Integer vulputate lectus blandit odio commodo, sit amet aliquam ex venenatis. Pellentesque ac mattis neque. Vivamus ut massa commodo, scelerisque enim vestibulum, porttitor turpis. Mauris dignissim vestibulum mi ac iaculis. Morbi turpis ante, bibendum eu ultrices sed, facilisis in ante. Etiam finibus, nisl at euismod varius, nulla erat convallis eros, non lacinia neque risus non orci. Fusce ac justo erat. Vivamus ut massa nunc. Integer commodo augue in eros mattis, at pretium odio egestas. Integer mauris felis, dapibus in condimentum eu, congue in elit. Cras dignissim mauris nunc, aliquet tincidunt ligula volutpat vel. Sed tristique varius tellus, vitae cursus tortor facilisis et. ",
	"Quisque et sapien vel ex rhoncus congue ac at odio. Vivamus a felis sit amet sem viverra eleifend. Maecenas elementum sagittis posuere. Nunc non sodales mi. Vestibulum sed volutpat enim, non aliquam sem. In id nibh magna. Nullam faucibus laoreet fringilla. Aliquam ac metus non justo dapibus interdum. Praesent et nisl sed turpis sollicitudin pellentesque sit amet id urna. Integer fringilla et risus quis pharetra. Sed malesuada metus quis rhoncus tempus. Nulla mollis dictum enim, non tristique sem varius vel. Pellentesque libero libero, gravida sit amet dapibus a, malesuada ut metus. Pellentesque egestas venenatis enim, vitae cursus sapien tincidunt ut. Fusce dignissim vitae nisi et interdum. Duis tincidunt nisl nulla, id convallis odio tincidunt eu. ",
	"Donec ut sapien quis est finibus rutrum eget a elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam mattis ex eu tincidunt ultricies. Curabitur eu tincidunt elit. Nunc eget facilisis ante. Morbi vestibulum, neque vel gravida elementum, velit felis consequat nibh, sit amet luctus sapien nibh vel elit. Phasellus et diam euismod, pulvinar justo ut, aliquam orci. Ut cursus eget dui eu malesuada. ",
	"Vivamus vel lorem sem. Vivamus vitae varius nulla, eget posuere augue. Vivamus eleifend ullamcorper feugiat. Morbi laoreet, tellus ac lacinia vehicula, ipsum augue fermentum ex, vel volutpat turpis diam id diam. Phasellus a condimentum mi. Phasellus rhoncus euismod mattis. Mauris ligula eros, rutrum id posuere vitae, pharetra sed tortor. Vestibulum efficitur mauris vel enim dictum, ac cursus velit volutpat. Curabitur cursus molestie diam id dictum. Sed quis porttitor enim, id tincidunt nisl. Quisque feugiat diam volutpat, posuere nulla vitae, congue leo. Morbi posuere elementum est, vitae faucibus diam suscipit in. ",
	"Proin ac nunc sed tortor hendrerit viverra. Phasellus lacus mauris, facilisis ut facilisis vitae, congue quis enim. Donec ultrices lectus sagittis neque imperdiet laoreet. Nam convallis sapien vitae euismod luctus. Phasellus nunc dolor, elementum et magna ac, auctor vehicula orci. Vestibulum dapibus dictum diam. Etiam mattis pharetra porttitor. Pellentesque sit amet nisl sed ex semper vestibulum. Nam viverra in metus eu hendrerit. ",
	"Maecenas ac metus risus. Integer placerat arcu nec mi vestibulum pretium. Sed porttitor, ipsum in convallis volutpat, urna nisi porta nunc, eu pulvinar nisi augue ornare nisl. Pellentesque viverra lacus non urna sodales, eu ultricies lacus tincidunt. Mauris sed urna vel sapien sagittis luctus ac et nisi. Pellentesque faucibus nunc tellus, porta vestibulum mi facilisis in. Morbi elementum malesuada leo, et luctus turpis. Etiam fermentum tincidunt ex a finibus. Duis ultricies arcu a commodo gravida. Maecenas bibendum arcu ut iaculis venenatis. Integer vulputate felis sodales felis fermentum, ac commodo magna maximus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
	"Aenean placerat, magna eu consectetur egestas, odio nisl dapibus orci, sit amet feugiat ligula magna quis ante. Maecenas pulvinar suscipit quam, id molestie nibh consequat quis. Fusce varius facilisis neque non vulputate. In tristique nunc non erat ornare, a tincidunt lorem elementum. Sed quis eros enim. Proin vel rutrum est, vitae dapibus risus. Nullam auctor nisi ex, in ultrices mauris consectetur sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer ac sem eget nisl vestibulum venenatis. ",
	"Nulla non ligula in purus imperdiet fringilla et ac lectus. Cras erat diam, dapibus at efficitur et, imperdiet in lorem. Pellentesque condimentum ac elit et viverra. Vestibulum dignissim mattis lectus, ut porta diam condimentum quis. Cras ac gravida urna, ut rhoncus tortor. In consequat iaculis elit ac sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam maximus ipsum sit amet efficitur efficitur. In iaculis mollis hendrerit. Duis ullamcorper urna quis condimentum fermentum. Vestibulum sed nunc lorem. Pellentesque dapibus diam in bibendum molestie. Nulla id finibus orci, eu venenatis sapien. Nulla ut lectus vitae purus consequat pharetra. Proin sed justo euismod, cursus sapien aliquet, placerat mauris. Vivamus a diam nec libero tempor vestibulum quis quis tortor. ",
	"Nam venenatis nulla est, sit amet molestie tellus scelerisque sit amet. Donec convallis ultricies dolor. Nam malesuada turpis id gravida scelerisque. Duis non mattis turpis. Praesent a ornare lorem. Donec nec tortor nec mauris dignissim cursus ac a lacus. Praesent id arcu aliquam, suscipit enim et, vestibulum ex. Integer in sapien erat. Aliquam nisl dui, faucibus sed lectus quis, feugiat blandit arcu. Ut ut tristique ante. In quis ante tincidunt, condimentum mi ac, congue neque. Nulla ac blandit dolor, eu egestas nibh. Suspendisse luctus ligula quis orci tincidunt, in rhoncus massa euismod. Aliquam tincidunt elementum cursus. Aenean tincidunt lorem vitae tempor eleifend. Phasellus pellentesque sem orci, at porttitor tortor vulputate eget. ",
	"Cras vitae eros elementum, pretium arcu at, porta nibh. Nunc sit amet ligula tempor nulla feugiat dignissim. Nullam at pellentesque nibh. Pellentesque a mauris vel nisl pulvinar malesuada id non velit. Donec auctor mi accumsan facilisis eleifend. Curabitur lacinia enim et risus sollicitudin porttitor. Proin tincidunt risus aliquam diam elementum tincidunt a quis quam. In dui diam, ultricies in elit vel, viverra hendrerit metus. Aenean sed sem in ante ultrices dignissim. Vivamus condimentum neque nec leo placerat ullamcorper. Suspendisse eu nulla quis purus suscipit commodo. ",
	"Nulla facilisi. Praesent maximus diam ex. Mauris non erat tincidunt, interdum ipsum et, pharetra lacus. Pellentesque quis tristique nibh, non posuere mi. Nunc aliquet aliquet tellus. Aliquam non ullamcorper elit. Nam a elit sed elit sollicitudin auctor. Quisque suscipit nibh vel commodo dignissim. Donec consectetur arcu in commodo venenatis. Aenean augue felis, pulvinar ac cursus ut, sollicitudin sodales metus. Donec commodo lacus eu iaculis interdum. ",
	"Donec luctus viverra nibh eget tincidunt. Nam sit amet egestas massa. Phasellus eu condimentum lorem. Vestibulum arcu est, pellentesque vel nulla sed, bibendum facilisis augue. Mauris condimentum, odio non semper sagittis, nisl metus blandit arcu, vitae varius leo sapien ultricies lacus. Quisque maximus, tellus at blandit sollicitudin, odio dui imperdiet est, eu scelerisque dui magna et justo. Morbi ac lorem vel ante venenatis hendrerit id quis nulla. Donec scelerisque vulputate ex vel aliquet. Fusce porta egestas lectus, eu luctus neque cursus vel. Etiam congue mattis est, id condimentum leo convallis et. Nunc nec feugiat nisi. In erat elit, vestibulum ut condimentum suscipit, accumsan sit amet velit. Curabitur ac arcu dui. Ut euismod metus eu luctus feugiat. Quisque lacinia, nunc sit amet sagittis laoreet, eros turpis convallis sem, eu aliquam nisi dui non ipsum. ",
	"Sed ac consectetur magna, vitae dapibus metus. Nullam id libero non nisl porta ornare sed at diam. Maecenas gravida quis justo ac semper. Nulla sodales leo quis augue mollis, pretium malesuada massa egestas. Duis non odio vitae diam gravida consectetur. In hac habitasse platea dictumst. Nulla facilisi. Praesent tincidunt, quam et tincidunt posuere, leo tellus faucibus enim, at posuere nisl mi nec felis. ",
	"Vestibulum sit amet mauris eget mauris pharetra venenatis. Sed turpis lectus, dignissim nec accumsan vel, elementum non libero. Proin rhoncus lobortis scelerisque. In in fringilla orci, eu sollicitudin erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean eu commodo erat, sit amet iaculis arcu. Nunc hendrerit ipsum diam, eget accumsan metus rhoncus tristique. Etiam in vestibulum felis. Nulla suscipit arcu et lorem vestibulum, at finibus nunc tristique. Curabitur viverra at lectus at blandit. Aenean convallis pharetra lorem eget aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
	"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean vestibulum mi eget justo euismod, sit amet semper neque efficitur. Nulla ligula leo, convallis in odio sit amet, feugiat suscipit arcu. Cras dignissim quam velit, eu facilisis augue gravida at. Nullam volutpat aliquet dolor, in auctor enim posuere ut. Nam eget placerat quam, eu porttitor enim. Phasellus viverra arcu eu porttitor sagittis. Praesent sagittis justo risus, id sodales elit fringilla nec. Integer commodo fringilla dignissim. Curabitur feugiat ligula a diam ultricies ullamcorper. Maecenas varius ex a aliquet fringilla. Praesent tristique elementum elit. Vivamus aliquam nibh nec finibus vulputate. ",
	"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce dignissim tortor vitae velit condimentum, sit amet blandit nulla euismod. Suspendisse elit risus, lacinia nec dapibus semper, iaculis nec orci. Maecenas at varius arcu. Mauris ullamcorper est arcu, sed ultricies libero tincidunt in. Integer quis lacus et elit finibus tempus sit amet vitae orci. Nam rutrum, lectus a tincidunt sagittis, enim est maximus sem, a venenatis est ligula ac erat. ",
	"Pellentesque blandit leo erat, vel iaculis libero placerat a. Ut in gravida eros. Fusce porttitor sapien nec ante maximus suscipit. Aenean eleifend nisl sed mauris egestas malesuada. Aenean risus erat, consequat in lobortis ac, posuere nec risus. Aenean volutpat nisi sit amet erat iaculis vestibulum. Suspendisse porttitor velit id maximus varius. Nam sollicitudin turpis eros, nec euismod sapien posuere in. Integer scelerisque fringilla nisl, quis sollicitudin elit. Proin vehicula lobortis nulla, pretium maximus mauris. Cras rutrum purus sit amet mauris tempus, vitae dapibus arcu feugiat. Proin a neque sit amet est suscipit mollis. ",
	"Sed eget ultricies lacus, vitae iaculis nunc. Quisque non nulla scelerisque, pulvinar odio at, venenatis orci. Nunc posuere tortor sapien, ac finibus risus feugiat et. Phasellus quis magna a est rutrum molestie. Fusce sit amet nibh ut sem scelerisque vehicula. Morbi ut ultricies lacus, ut commodo lectus. Cras semper leo at commodo porta. Aenean aliquam nulla a suscipit pretium. ",
	"Cras non condimentum neque. Etiam vitae nisl facilisis, mattis diam consectetur, iaculis eros. Mauris nec velit vitae nibh convallis malesuada. Nullam leo risus, aliquet elementum fringilla et, efficitur ut arcu. Aenean sed lorem mattis, tempus lorem nec, interdum felis. Maecenas feugiat feugiat pharetra. Etiam at odio egestas, elementum ante vitae, aliquam ante. In consequat semper sagittis. Vivamus fringilla augue ac ligula egestas, nec efficitur urna imperdiet. Morbi nec massa blandit lectus aliquet scelerisque. Curabitur finibus tortor sed nisl blandit, id vulputate nibh dignissim. ",
	"Suspendisse a ultricies mauris, sit amet maximus neque. Ut eget eros id sapien fringilla pharetra ut vitae dui. Nunc a felis quis orci varius feugiat. Pellentesque at urna in tellus dignissim fringilla. In id sapien lorem. Aliquam erat volutpat. Fusce convallis ligula pulvinar felis ornare faucibus. Vestibulum eget gravida justo, eget semper turpis. In ultrices orci vitae faucibus gravida. Aliquam ac nulla ipsum. Vivamus finibus nisl placerat velit imperdiet congue. Etiam vel arcu quis elit eleifend condimentum. Sed tincidunt augue nibh, eget iaculis neque maximus vitae. ",
	"Praesent turpis nibh, varius et nisi vitae, mattis blandit lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris elit tellus, faucibus vel sem non, tristique imperdiet nulla. Ut lobortis porttitor volutpat. Pellentesque ut pellentesque erat. Nunc eleifend augue quis dignissim blandit. Donec ipsum tortor, rhoncus nec cursus quis, ultrices sed nisl. Aliquam ac aliquet ipsum, vitae cursus erat. Curabitur velit ex, placerat vitae aliquam quis, semper id massa. Aenean vitae pellentesque quam, nec sollicitudin mauris. Proin eu porttitor velit, sed vestibulum orci. ",
	"Donec mollis augue at pharetra pellentesque. Nullam a libero ac dui convallis ultrices sit amet blandit risus. Sed dolor ipsum, faucibus et dictum egestas, cursus in urna. Mauris quis ante dictum, eleifend leo ut, euismod neque. Vivamus eget placerat metus, vel rhoncus diam. Cras fermentum augue vel vehicula aliquet. Nulla facilisi. Donec pellentesque bibendum dui, ut egestas urna pretium non. In hac habitasse platea dictumst. Nulla et justo nec neque elementum condimentum. Vestibulum maximus felis vel felis convallis mollis eget sed neque. Nullam in ex sapien. Sed hendrerit lacus sed metus tempus semper. Duis fermentum orci vel eleifend condimentum. "
};
#endif
